server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: oauth2-client-app
            clientSecret: TCUwfHOUaTMdovquaEOeG8H4pZah7X6q
            clientName: oauth2-client-app
            authorizationGrantType: password
            scope: openid,profile
            clientAuthenticationMethod: client_secret_basic
            provider: keycloak

        provider:
          keycloak:
            authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            issuerUri: http://localhost:8080/realms/oauth2 #인가서버의 기본 URI
            userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            userNameAttribute: preferred_username


